version: '3.8'

services:
  app:
    container_name: billing
    build: ./
    command: ./billing
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=111

  db:
    container_name: billing_db
    restart: always
    build: ./db
    environment:
      POSTGRES_PASSWORD: 111
      POSTGRES_DB: billing
      POSTGRES_USER: postgres
    ports:
      - 5432